forecast/urls.py
"""Схемы URL для forecast"""

from django.urls import path

from .views import WeatherForecastView, clear_search

app_name = 'forecast'

urlpatterns = [
    path('', WeatherForecastView.as_view(), name='weather_forecast'),
    path('clear-search/', clear_search, name='clear_search'),
]

weather/urls.py
from django.contrib import admin
from django.urls import include, path

from forecast.views import pageNotFound
from weather import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forecast.urls', namespace='forecast'))
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

handler404 = pageNotFound
handler403 = pageNotFound

forecast/models.py
from django.db import models

# Create your models here.

forecast/forms.py
from django import forms


class CityNameForm(forms.Form):
    """ Форма ввода названия города по которому необходимо получить прогноз погоды """

    city = forms.CharField(
        max_length=150, required=True,
        widget=forms.TextInput(attrs={'placeholder': 'введите название города'}),
        label='city',
    )

forecast/views.py
from django.http import (HttpResponse, HttpResponseNotFound,
                         HttpResponseRedirect)
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from forecast.services.forecast import ForeCastService

from .forms import CityNameForm


class WeatherForecastView(View):
    """ Представление главной страницы прогноза погоды """

    title = 'Прогноз погоды'
    form_class = CityNameForm
    forecast_service = ForeCastService()

    def get(self, request) -> HttpResponse:
        date_and_temperature_list = [{'date': day, 'temperature': '-'} for day in self.forecast_service.weekday]

        context = {
            'form': self.form_class,
            'title': self.title,
            'date_and_temperature_list': date_and_temperature_list,
        }

        return render(request=request, template_name='forecast/main.html', context=context)

    def post(self, request) -> HttpResponse:
        context = {
            'form': self.form_class(request.POST),
            'title': self.title,
        }

        try:
            date_and_temperature_list = self.forecast_service.get_weather_forecast_in_city(
                city_name=request.POST['city']
            )
            context['date_and_temperature_list'] = date_and_temperature_list
        except Exception as err:
            context['date_and_temperature_list'] = self.forecast_service.create_date_and_temperature_list()
            context['error'] = str(err)

        return render(request=request, template_name='forecast/main.html', context=context)


def clear_search(request) -> HttpResponseRedirect:
    """ Функция для очистки полей формы поиска CityNameForm """

    redirect_url = reverse('forecast:weather_forecast')
    return HttpResponseRedirect(redirect_url)


def pageNotFound(request, exception) -> HttpResponseNotFound:
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

forecast/templates/forecast/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %} {% endblock title %}</title>

        <!-- Base CSS -->
        <link rel="stylesheet" href="{% static 'forecast/css/base.css' %}" xmlns="http://www.w3.org/1999/html">
        {% block css %} {% endblock %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    </head>

    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    <!-- Header -->
    <header class="header">
        <div class="header__container">
            <div class="header__container-logo">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#E8F0FE" class="bi bi-cloud-sun me-2" viewBox="0 0 16 16"><path d="M7 8a3.5 3.5 0 0 1 3.5 3.555.5.5 0 0 0 .624.492A1.503 1.503 0 0 1 13 13.5a1.5 1.5 0 0 1-1.5 1.5H3a2 2 0 1 1 .1-3.998.5.5 0 0 0 .51-.375A3.502 3.502 0 0 1 7 8zm4.473 3a4.5 4.5 0 0 0-8.72-.99A3 3 0 0 0 3 16h8.5a2.5 2.5 0 0 0 0-5h-.027z"></path><path d="M10.5 1.5a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0v-1zm3.743 1.964a.5.5 0 1 0-.707-.707l-.708.707a.5.5 0 0 0 .708.708l.707-.708zm-7.779-.707a.5.5 0 0 0-.707.707l.707.708a.5.5 0 1 0 .708-.708l-.708-.707zm1.734 3.374a2 2 0 1 1 3.296 2.198c.199.281.372.582.516.898a3 3 0 1 0-4.84-3.225c.352.011.696.055 1.028.129zm4.484 4.074c.6.215 1.125.59 1.522 1.072a.5.5 0 0 0 .039-.742l-.707-.707a.5.5 0 0 0-.854.377zM14.5 6.5a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1z"></path></svg>
            </div>
        </div>
    </header>

            <!-- Контент страницы -->
        {% block content %} {% endblock %}
        <script src="https://unpkg.com/htmx.org@1.9.4"></script>
    </body>

    {% block script %} {% endblock script %}
</html>

forecast/templates/forecast/main.html
{% extends 'forecast/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'forecast/css/main.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<div class="city">
    <h1></h1>
    <form method="post">
        {% csrf_token %}

        <div class="form__clear">
        {{form.city}}
        <a href="{% url 'forecast:clear_search' %}"><button type="button" class="btn btn-primary btn-x">X</button></a>
        </div>

        <button type="submit" class="btn btn-primary btn-block btn-large">Получить прогноз</button>
    </form>
    <div class="forecast">
        {% for dt in date_and_temperature_list %}
            <div class="forecast__days">{{dt.date|date:"d"}} {{dt.date|date:"D"}}
                        <br>{{dt.temperature|default:"-"}}&#8451
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

{% block script %}
    {% if error %}
        <script>
            setTimeout(() => {  alert("К сожалению указанный город не удалось определить"); }, 200);
        </script>
    {% endif %}
{% endblock script %}